#!/bin/bash

# Function for sending notifications with AwesomeWM's naughty
function send_notification() {
    volume=$(pamixer --get-volume)
    
    # Select the right icon based on volume level
    if [ "$volume" -eq 0 ]; then
        icon="audio-volume-muted"
    elif [ "$volume" -lt 30 ]; then
        icon="audio-volume-low"
    elif [ "$volume" -lt 70 ]; then
        icon="audio-volume-medium"
    else
        icon="audio-volume-high"
    fi
    
    # Send notification through notify-send
    # AwesomeWM's naughty will pick these up
    notify-send -a "changevolume" -u low -h int:value:"$volume" \
                -i "$icon" "Volume: ${volume}%" -t 2000 -r 9993
}

# Main cases
case $1 in
    up)
        # Set the volume on (if it was muted)
        pamixer -u
        pamixer -i 2 --allow-boost
        send_notification
        ;;
    down)
        pamixer -u
        pamixer -d 2 --allow-boost
        send_notification
        ;;
    mute)
        pamixer -t
        if $(pamixer --get-mute); then
            notify-send -i "audio-volume-muted" -a "changevolume" \
                        -t 2000 -r 9993 -u low "Muted"
        else
            send_notification
        fi
        ;;
esac
