#!/bin/bash

function send_notification() {
    volume=$(pamixer --get-volume)
    
    # Create an XFCE4-style volume bar with Unicode block characters
    # This creates a smoother, more modern-looking slider
    bar_length=20
    filled_length=$(( $volume * $bar_length / 100 ))
    
    # Create a more stylized progress bar with background color
    bar="<span color='#202020'>▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁</span>"
    
    # Create the filled part with GitHub blue
    if [ $filled_length -gt 0 ]; then
        filled=""
        for ((i=0; i<$filled_length; i++)); do
            filled="${filled}▁"
        done
        
        # Insert the filled part at the beginning with color
        bar="<span color='#539bf5'>${filled}</span>${bar:$((filled_length*24))}"
    fi
    
    # Create a notification through awesome-client using naughty
    lua_command="
    local naughty = require('naughty')
    
    -- Always use the same notification ID to replace previous ones
    if not volume_notification_id then
        volume_notification_id = 9993
    end
    
    -- Create or update notification
    local notification = naughty.notify({
        title = 'Volume: ${volume}%',
        text = '${bar}',
        icon = 'volume-$1',
        preset = naughty.config.presets.low,
        replaces_id = volume_notification_id,
        timeout = 2,
        id = volume_notification_id,
        markup = 'pango'  -- Enable HTML/Pango markup
    })
    
    -- Update the global ID for next time
    volume_notification_id = notification.id
    "
    
    echo "$lua_command" | awesome-client
}

case $1 in
up)
    # Set the volume on (if it was muted)
    pamixer -u
    pamixer -i 2 --allow-boost
    send_notification up
    ;;
down)
    pamixer -u
    pamixer -d 2 --allow-boost
    send_notification down
    ;;
mute)
    pamixer -t
    if $(pamixer --get-mute); then
        # Create a mute notification
        lua_command="
        local naughty = require('naughty')
        
        -- Always use the same notification ID to replace previous ones
        if not volume_notification_id then
            volume_notification_id = 9993
        end
        
        -- Create or update notification
        local notification = naughty.notify({
            title = 'Volume',
            text = 'Muted',
            icon = 'volume-mute',
            preset = naughty.config.presets.low,
            replaces_id = volume_notification_id,
            timeout = 2,
            id = volume_notification_id
        })
        
        -- Update the global ID for next time
        volume_notification_id = notification.id
        "
        echo "$lua_command" | awesome-client
    else
        send_notification up
    fi
    ;;
esac
